-- Tabla: DEPARTAMENTO
CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO INTEGER PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL
);

-- Tabla: EMPLEADO
CREATE TABLE EMPLEADO (
    ID_EMPLEADO INTEGER PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    CARGO VARCHAR(45) NOT NULL,
    SALARIO DECIMAL(10,2) NOT NULL,
    FECHA_CONTRATACION DATE NOT NULL,
    ID_DEPARTAMENTO INTEGER,
    FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO)
);

-- Tabla: PROVEEDOR
CREATE TABLE PROVEEDOR (
    ID_PROVEEDOR INTEGER PRIMARY KEY,
    NOMBRE VARCHAR(200) NOT NULL,
    CONTACTO VARCHAR(100) NOT NULL,
    PRODUCTO_SUMINISTRADO VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(200)
);

-- Tabla: PRODUCTO
CREATE TABLE PRODUCTO (
    ID_PRODUCTO INTEGER PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    TIPO VARCHAR(50) NOT NULL,
    PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
    ID_PROVEEDOR INTEGER,
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR)
);

-- Tabla: INVENTARIO
CREATE TABLE INVENTARIO (
    ID_INVENTARIO INTEGER PRIMARY KEY,
    ID_PRODUCTO INTEGER,
    CANTIDAD INTEGER NOT NULL,
    UBICACION VARCHAR(100),
    FECHA_ULTIMA_ACTUALIZACION DATETIME,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);

-- Tabla: MAQUINARIA
CREATE TABLE MAQUINARIA (
    ID_MAQUINARIA INTEGER PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(45) NOT NULL CHECK (ESTADO IN ('Activo', 'Mantenimiento', 'Inactivo')),
    FECHA_ADQUISICION DATE,
    HORAS_USO INTEGER
);
